trigger:
- master
- preprod

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ASPNETCORE_ENVIRONMENT: 'Preprod'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Installer l'outil EF Core globalement
- script: dotnet tool install --global dotnet-ef
  displayName: 'Install EF Core Tools'

# Restore
- script: dotnet restore IccPlanner/IccPlanner.csproj
  displayName: 'Restore NuGet packages'

# Build
- script: dotnet build IccPlanner/IccPlanner.csproj --configuration $(buildConfiguration)
  displayName: 'Build solution'


 #Appliquer la migration EF Core
- script: |
   export PATH="$PATH:/root/.dotnet/tools"
   dotnet ef migrations script -o migrations.sql --project Infrastructure/Infrastructure.csproj --startup-project IccPlanner/IccPlanner.csproj 
  displayName: 'Run EF Core migrations'
  env:
   ASPNETCORE_ENVIRONMENT: $(ASPNETCORE_ENVIRONMENT) 

- script: cp migrations.sql $(Build.ArtifactStagingDirectory)
  displayName: 'Copy migrations.sql to artifact staging directory'

# Publier le script comme artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'migrations.sql'
    ArtifactName: 'EFMigrationScript'
    publishLocation: 'Container'   

# Publish
- script: dotnet publish  IccPlanner/IccPlanner.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish project'

# Déploiement préprod
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ApiRessourceV01'
    appname: 'IccStartPlannrApiV01'
    package: '$(Build.ArtifactStagingDirectory)/publish'

# Déploiement prod
#- task: AzureWebApp@1
#  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
#  inputs:
#    azureSubscription: 'MaConnexionAzure'
#    appName: 'mon-api-prod'
#    package: '$(Build.ArtifactStagingDirectory)/publish'#
