//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Ressources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Availability not found. Please try again later or contact the support team..
        /// </summary>
        public static string AVAILAIBILITY_NOT_FOUND {
            get {
                return ResourceManager.GetString("AVAILAIBILITY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad request.
        /// </summary>
        public static string BAD_REQUEST {
            get {
                return ResourceManager.GetString("BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} must not contain any null values..
        /// </summary>
        public static string CANNOT_CONTAIN_NULL {
            get {
                return ResourceManager.GetString("CANNOT_CONTAIN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can no longer modify this availability because the event date has passed..
        /// </summary>
        public static string CANT_DELETE_AVAIBILITY {
            get {
                return ResourceManager.GetString("CANT_DELETE_AVAIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date(s) are required when the program is punctual..
        /// </summary>
        public static string DATES_REQUIRED {
            get {
                return ResourceManager.GetString("DATES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Days.
        /// </summary>
        public static string DAYS {
            get {
                return ResourceManager.GetString("DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more days are required when the program is recurring..
        /// </summary>
        public static string DAYS_REQUIRED {
            get {
                return ResourceManager.GetString("DAYS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This ministry is associated with one or more departments. Deleting it will also automatically delete all departments linked to it..
        /// </summary>
        public static string DE_Ministry {
            get {
                return ResourceManager.GetString("DE_Ministry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The department.
        /// </summary>
        public static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Department.
        /// </summary>
        public static string DEPARTMENT_ {
            get {
                return ResourceManager.GetString("DEPARTMENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The department « {0} » already exists..
        /// </summary>
        public static string DEPARTMENT_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more department identifiers are invalid..
        /// </summary>
        public static string DEPARTMENT_INVALID_IDS {
            get {
                return ResourceManager.GetString("DEPARTMENT_INVALID_IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Department name.
        /// </summary>
        public static string DEPARTMENT_NAME {
            get {
                return ResourceManager.GetString("DEPARTMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This department not exist..
        /// </summary>
        public static string DEPARTMENT_NOT_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The department « {0} » already has a program «{1} » of type « {2} »..
        /// </summary>
        public static string DEPARTMENT_PROGRAM_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_PROGRAM_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This department not exist..
        /// </summary>
        public static string DEPARTMENT_PROGRAM_NOT_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_PROGRAM_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service display name.
        /// </summary>
        public static string DISPLAY_NAME {
            get {
                return ResourceManager.GetString("DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End time.
        /// </summary>
        public static string END_TIME {
            get {
                return ResourceManager.GetString("END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the days in English. (e.g., Monday, Tuesday, etc.) .
        /// </summary>
        public static string ENGLISH_DAY {
            get {
                return ResourceManager.GetString("ENGLISH_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown error. Please try again later..
        /// </summary>
        public static string ERROR_UNDEFINED {
            get {
                return ResourceManager.GetString("ERROR_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} « {PropertyValue} » already exist..
        /// </summary>
        public static string EXIST {
            get {
                return ResourceManager.GetString("EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} « {1} » already exist..
        /// </summary>
        public static string EXIST_Pro_Val {
            get {
                return ResourceManager.GetString("EXIST_Pro_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file is too large, the maximum allowed size is {0} MB..
        /// </summary>
        public static string FILE_TOO_LARGE {
            get {
                return ResourceManager.GetString("FILE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forbidden. You do not have the necessary permissions to access this resource..
        /// </summary>
        public static string FORBIDDEN_ACCESS {
            get {
                return ResourceManager.GetString("FORBIDDEN_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} must be greater than {ComparisonValue}..
        /// </summary>
        public static string GREATER_THEN {
            get {
                return ResourceManager.GetString("GREATER_THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each date must be in a valid format (yyyy-MM-dd)..
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} &apos;{CollectionIndex}&apos; is invalid..
        /// </summary>
        public static string INVALID_ENTRIES {
            get {
                return ResourceManager.GetString("INVALID_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} is invalid..
        /// </summary>
        public static string INVALID_ENTRY {
            get {
                return ResourceManager.GetString("INVALID_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file data is invalid. Please check the columns and their content..
        /// </summary>
        public static string INVALID_FILE_DATA {
            get {
                return ResourceManager.GetString("INVALID_FILE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file extension is not allowed..
        /// </summary>
        public static string INVALID_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("INVALID_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file is not a valid Excel file..
        /// </summary>
        public static string INVALID_FILE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gender must be M or F..
        /// </summary>
        public static string INVALID_GENDER {
            get {
                return ResourceManager.GetString("INVALID_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid login attempt..
        /// </summary>
        public static string INVALID_LOGIN_ATTEMPT {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name must only contain letters..
        /// </summary>
        public static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On line {0}.
        /// </summary>
        public static string INVALID_ON {
            get {
                return ResourceManager.GetString("INVALID_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number must contain only digits. .
        /// </summary>
        public static string INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid program type. Allowed values are:  Recurring ,Punctual .
        /// </summary>
        public static string INVALID_PRG_TYPE {
            get {
                return ResourceManager.GetString("INVALID_PRG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is invalid..
        /// </summary>
        public static string INVALID_VALUE {
            get {
                return ResourceManager.GetString("INVALID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} must not exceed {MaxLength} characters..
        /// </summary>
        public static string MAX_LENGTH {
            get {
                return ResourceManager.GetString("MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} must not exceed {1} characters.
        /// </summary>
        public static string MAXLENGTH {
            get {
                return ResourceManager.GetString("MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Members.
        /// </summary>
        public static string MEMBER {
            get {
                return ResourceManager.GetString("MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The member&apos;s arrival time is invalid or must not exceed the program start time..
        /// </summary>
        public static string MEMBER_ARIVAL_TIME {
            get {
                return ResourceManager.GetString("MEMBER_ARIVAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The member&apos;s arrival time.
        /// </summary>
        public static string MEMBER_ARRIVAL {
            get {
                return ResourceManager.GetString("MEMBER_ARRIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} must be greater than or equal to {ComparisonValue}..
        /// </summary>
        public static string MIN_VALUE {
            get {
                return ResourceManager.GetString("MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ministry.
        /// </summary>
        public static string MINISTRY {
            get {
                return ResourceManager.GetString("MINISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ministry name .
        /// </summary>
        public static string MINISTRY_NAME {
            get {
                return ResourceManager.GetString("MINISTRY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following columns are required: PRENOM, SEXE, CONTACT..
        /// </summary>
        public static string MISSING_REQUIRED_COLUMN {
            get {
                return ResourceManager.GetString("MISSING_REQUIRED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The ministry name « {0} » already exists..
        /// </summary>
        public static string MJ_MinistryNameExist {
            get {
                return ResourceManager.GetString("MJ.MinistryNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This ministry name is already assigned; modification is not possible..
        /// </summary>
        public static string MO_MinistryNameExist {
            get {
                return ResourceManager.GetString("MO.MinistryNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have the necessary permissions to edit this program. .
        /// </summary>
        public static string MO_PrgNonAutor {
            get {
                return ResourceManager.GetString("MO_PrgNonAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select one or more {PropertyName}.
        /// </summary>
        public static string MUST_CHOOSE {
            get {
                return ResourceManager.GetString("MUST_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  {PropertyName} is already taken..
        /// </summary>
        public static string NAME_EXISTS {
            get {
                return ResourceManager.GetString("NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number of service(s).
        /// </summary>
        public static string NBR_SERVICE {
            get {
                return ResourceManager.GetString("NBR_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  {0} : No matching entry found for the specified value..
        /// </summary>
        public static string NOT_EXIST {
            get {
                return ResourceManager.GetString("NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} cannot be null..
        /// </summary>
        public static string NOT_NULL {
            get {
                return ResourceManager.GetString("NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot add this service: the program already has one scheduled on this date and at this time..
        /// </summary>
        public static string PGM_SERVICE_EXIST {
            get {
                return ResourceManager.GetString("PGM_SERVICE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This program does not exist..
        /// </summary>
        public static string PRG_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRG_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The program.
        /// </summary>
        public static string PROGRAM {
            get {
                return ResourceManager.GetString("PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Program.
        /// </summary>
        public static string PROGRAM_ {
            get {
                return ResourceManager.GetString("PROGRAM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The program name.
        /// </summary>
        public static string PROGRAM_NAME {
            get {
                return ResourceManager.GetString("PROGRAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The program type.
        /// </summary>
        public static string PROGRAM_TYPE {
            get {
                return ResourceManager.GetString("PROGRAM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service.
        /// </summary>
        public static string SERVICE {
            get {
                return ResourceManager.GetString("SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service.
        /// </summary>
        public static string SERVICE_ {
            get {
                return ResourceManager.GetString("SERVICE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your availability for this service has already been recorded..
        /// </summary>
        public static string SERVICE_ALREADY_CHOSEN {
            get {
                return ResourceManager.GetString("SERVICE_ALREADY_CHOSEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to register this service: a service named «{0}» already exists between {1} and {2}..
        /// </summary>
        public static string SERVICE_EXISTS {
            get {
                return ResourceManager.GetString("SERVICE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot set your availability for this time slot because you are not part of the associated department..
        /// </summary>
        public static string SERVICE_NOT_AVAILABITY {
            get {
                return ResourceManager.GetString("SERVICE_NOT_AVAILABITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service Identifier.
        /// </summary>
        public static string SERVICE_PRG {
            get {
                return ResourceManager.GetString("SERVICE_PRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The short name .
        /// </summary>
        public static string SHORT_NAME {
            get {
                return ResourceManager.GetString("SHORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start time.
        /// </summary>
        public static string START_TIME {
            get {
                return ResourceManager.GetString("START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized access..
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User account locked out. Try again in a few minutes..
        /// </summary>
        public static string USER_IS_LOCKED_OUT {
            get {
                return ResourceManager.GetString("USER_IS_LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: User not found..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {PropertyName} must be valid and not in the future..
        /// </summary>
        public static string VAILID_DATE {
            get {
                return ResourceManager.GetString("VAILID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each day must be a valid day of the week (e.g., Monday, Tuesday, etc.) when the program is recurring. Please enter the days in English..
        /// </summary>
        public static string VALID_DAYS {
            get {
                return ResourceManager.GetString("VALID_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more validation errors occurred. Please check your input and try again..
        /// </summary>
        public static string VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("VALIDATION_FAILED", resourceCulture);
            }
        }
    }
}
