//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Ressources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file is too large, the maximum allowed size is {0} MB..
        /// </summary>
        public static string FILE_TOO_LARGE {
            get {
                return ResourceManager.GetString("FILE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file data is invalid. Please check the columns and their content..
        /// </summary>
        public static string INVALID_FILE_DATA {
            get {
                return ResourceManager.GetString("INVALID_FILE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file extension is not allowed..
        /// </summary>
        public static string INVALID_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("INVALID_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file is not a valid Excel file..
        /// </summary>
        public static string INVALID_FILE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gender must be M or F..
        /// </summary>
        public static string INVALID_GENDER {
            get {
                return ResourceManager.GetString("INVALID_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name must only contain letters..
        /// </summary>
        public static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On line {0}.
        /// </summary>
        public static string INVALID_ON {
            get {
                return ResourceManager.GetString("INVALID_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number must contain only digits. .
        /// </summary>
        public static string INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following columns are required: PRENOM, SEXE, CONTACT..
        /// </summary>
        public static string MISSING_REQUIRED_COLUMN {
            get {
                return ResourceManager.GetString("MISSING_REQUIRED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The field {0} cannot be null..
        /// </summary>
        public static string NOT_NULL {
            get {
                return ResourceManager.GetString("NOT_NULL", resourceCulture);
            }
        }
    }
}
