name: Build and deploy ASP.Net Core app to Azure Web App - iccAgendaApiDev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore API dependencies
        run: dotnet restore ./Api/IccPlanner.Api.csproj

      - name: Build API only
        run: dotnet build ./Api/IccPlanner.Api.csproj --configuration Release

      - name: Publish API only
        run: dotnet publish ./Api/IccPlanner.Api.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8BA9F05BB00443DB88EC35ABFC15C83E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_499C005CEEB24284A49E0B28D0FA9039 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE164A816E614A71A04D77F02B32FD88 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'iccAgendaApiDev'
          slot-name: 'Production'
          package: .
